# Site settings
title: Empty Thoughts
description: > # this means to ignore newlines until the next key.
  The thoughts of a madman.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://empty.rocks" # the base hostname & protocol for your site
twitter_username: the_empty
github_username: theempty
highlighter: rouge

# Build settings
markdown: kramdown
